core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),

    path("cash-in/", views.CashInFlow.as_view(), name="cash-in"),
    path("cash-out/", views.CashoutFlow.as_view(), name="cash-out"),

    path("statement/", views.Statement.as_view(), name="statement"),

    path("cash-in-detail/", views.CashInDetail.as_view(), name="cash-in-detail"),
    path("cash-out-detail/", views.CashOutDetail.as_view(), name="cash-out-detail"),

    path("cash-in-update/<int:pk>/", views.CashInUpdate.as_view(), name="cash-in-update"),
    path("cash-in-delete/<int:pk>/", views.CashInDelete.as_view(), name="cash-in-delete"),

    path("cash-out-update/<int:pk>/",views.CashOutUpdate.as_view(), name="cash-out-update"),
    path("cash-out-delete/<int:pk>/",views.CashOutDelete.as_view(),name="cash-out-delete"),
    
    path("category/", views.CategoryView.as_view(), name="category"),
    path("category-add/", views.CategoryAdd.as_view(), name="category-add"),
    path("category-update/<int:pk>/", views.CategoryUpdate.as_view(), name="category-update"),
    path("category-delete/<int:pk>/", views.CategoryDelete.as_view(), name="category-delete"),
    
    path("search/", views.SearchView.as_view(), name="search"),
    path("filter/", views.FilterView.as_view(), name="filter"),

    path('calculator/', views.CalculatorView.as_view(), name='calculator'),
    path('todo/', views.TodoView.as_view(), name='todo'),
    
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
]

spend_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('core.urls')),
    path("", include('accounts.urls')),
    # path('accounts/login/', views.LoginView.as_view(), name="login"),
    # path('accounts/logout/', views.LogoutView.as_view(), name="logout"),

    

]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

core/forms.py
from django import forms
from .models import *
import datetime


class CashInFLowForm(forms.ModelForm):
    class Meta:
        model = CashIn
        exclude = ["modified_at", "user"]
        widgets = {
            "date": forms.DateInput(
                attrs={"type": "date", "class": "form-control", "format": "%d %b %Y"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["amount"].widget.attrs.update({"class": "form-control"})
        self.fields["mode"].widget.attrs.update({"class": "form-control"})
        self.fields["note"].widget.attrs.update({"class": "form-control"})
        self.fields["type"].widget.attrs.update({"class": "form-control"})

        self.fields["type"].label = "Income Type"
        self.fields["mode"].label = "Income Mode"

        self.fields["date"].initial = datetime.date.today()


class CashOutFlowForm(forms.ModelForm):
    # category = forms.ChoiceField()
    category = forms.ModelChoiceField(queryset=Category.objects.all())

    class Meta:
        model = CashOut
        fields = ["amount", "mode", "pay_to", "category", "remarks", "date"]

        widgets = {
            "date": forms.DateInput(
                attrs={"type": "date", "class": "form-control", "format": "%d %b %Y"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].initial = Category.objects.first()

        self.fields["amount"].widget.attrs.update({"class": "form-control", "placeholder": "Enter Your Payment Amount"})
        self.fields["mode"].widget.attrs.update({"class": "form-control"})
        self.fields["pay_to"].widget.attrs.update({"class": "form-control", "placeholder": "Enter Whom To Pay"})
        self.fields["category"].widget.attrs.update({"class": "form-control"})
        self.fields["remarks"].widget.attrs.update({"class": "form-control", "placeholder": "Enter Your Remarks For Your Payment"})
        self.fields["pay_to"].label = "Pay To"
        self.fields["mode"].label = "Payment Mode"

        self.fields['category'].help_text = "If You Haven't Created Your Category Yet Click on "

        self.fields["date"].initial = datetime.date.today()
    
   
class CategoryAddForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name"]

templates/forms/add_category.html
{% extends 'base/base.html' %}

{% block content %}
<div class="col-12 grid-margin stretch-card" style="color: aqua; justify-content: center;">
    <h1>Add New Category</h1>
</div>
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">

            <form class="forms-sample" method="POST">
                {% csrf_token %}

                {{form.as_p}}

                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <a class="btn btn-dark" href="{% url 'category' %}">Cancel</a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/forms/cash_in_form.html
{% extends 'base/base.html' %}

{% block content %}
<div class="col-12 grid-margin stretch-card" style="color: aquamarine; justify-content: center;">
    <h1>Add New Income</h1>
</div>
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{message}}
            </div>
            {% endfor %}
            {% endif %}

            <form class="forms-sample" method="POST">
                {% csrf_token %}

                {{form.as_p}}

                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <a class="btn btn-dark" href="{% url 'cash-in-detail' %}">Cancel</a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/forms/cash_out_form.html
{% extends 'base/base.html' %}

{% block content %}
<div class="col-12 grid-margin stretch-card" style="color: aquamarine; justify-content: center;">
    <h1>Add New Payment</h1>
</div>
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{message}}
            </div>
            {% endfor %}
            {% endif %}

            {% comment %} <form class="forms-sample" method="POST">
                {% csrf_token %}

                {{form.as_p}}

                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <a class="btn btn-dark" href="{% url 'cash-out-detail' %}">Cancel</a>
            </form> {% endcomment %}

            <form class="forms-sample" method="POST">
                {% csrf_token %}

                <p>
                    <label for="{{form.amount.id_for_label}}">{{form.amount.label}}:</label>
                    {{form.amount}}
                    <div style="color: brown;">{{form.amount.errors}}</div>
                </p>
                <p>
                    <label for="{{form.mode.id_for_label}}">{{form.mode.label}}:</label>
                    {{form.mode}} 
                </p>
                <p>
                    <label for="{{form.pay_to.id_for_label}}">{{form.pay_to.label}}:</label>
                    {{form.pay_to}}
                </p>
                <p>
                    <label for="{{form.category.id_for_label}}">{{form.category.label}}:</label>
                    <select name="{{form.category.name}}" class="form-control" id="{{form.category.id_for_label}}">
                        {% for category in categories %}
                        <option value="{{category.id}}">{{ category.name }}</option>
                        {% endfor %}
                    </select>
                    <span style="color: cornflowerblue;">{{form.category.help_text}}</span> <a href="{% url 'category' %}" style="text-decoration: none;">ADD NEW CATEGORY</a> <span style="color: cornflowerblue;">e.g. 'Shopping', 'Food', 'Groceries'</span>
                </p>
                <p>
                    <label for="{{form.remarks.id_for_label}}">{{form.remarks.label}}:</label>
                    {{form.remarks}}
                </p>
                <p>
                    <label for="{{form.date.id_for_label}}">{{form.date.label}}:</label>
                    {{form.date}}
                </p>

                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <a class="btn btn-dark" href="/cash-out-detail/">Cancel</a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}
{% comment %} <p>
    <label for="id_category">Category:</label>
    <select name="category" class="form-control" id="id_category">
        {% for category in categories %}
        <option value="{{category.id}}">{{ category.name }}</option>
        {% endfor %}
    </select>
</p> {% endcomment %}

templates/forms/delete_cash_in.html
{% extends 'base/base.html' %}

{% block content %}
<div class="col-12 grid-margin stretch-card delete-confirmation" style="justify-content: center;">
    <h1>Delete Your Income Record?</h1>
</div>
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" method="POST">
                {% csrf_token %}

                <h4>Are you sure you want to delete this record? This action cannot be undone and removes data from the server.</h4>

                <button type="submit" class="btn btn-primary mr-2">YES</button>
                <a class="btn btn-dark" href="{% url 'cash-in-detail' %}">Cancel</a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/forms/delete_cash_out.html
{% extends 'base/base.html' %}

{% block content %}
<div class="col-12 grid-margin stretch-card delete-confirmation" style="justify-content: center;">
    <h1>Delete Your Payment Record?</h1>
</div>
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" method="POST">
                {% csrf_token %}

                <h4>Are you sure you want to delete this record? This action cannot be undone and removes data from the server.</h4>

                <button type="submit" class="btn btn-primary mr-2">YES</button>
                <a class="btn btn-dark" href="{% url 'cash-out-detail' %}">Cancel</a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/forms/delete_category.html
{% extends 'base/base.html' %}

{% block content %}
<div class="col-12 grid-margin stretch-card delete-confirmation" style="justify-content: center;">
    <h1>Delete Category?</h1>
</div>
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" method="POST">
                {% csrf_token %}

                <h4>Are you sure you want to delete this record? This action cannot be undone and removes data from the server.</h4>

                <button type="submit" class="btn btn-primary mr-2">YES</button>
                <a class="btn btn-dark" href="{% url 'category' %}">Cancel</a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}